Now the attribute resolver is failing for many tests:
cls = <class 'app.core.authz.resolvers.DataProductDatasetAssociationResolver'>, db = <sqlalchemy.orm.session.Session object at 0x7f69e01a6f30>, id_ = UUID('f669e1a1-d7e8-4ec4-80ca-722afb360fe5')

    @classmethod
    def resolve_domain(
        cls,
        db: Session,
        id_: str,
    ) -> str:
        if id_ == cls.DEFAULT or cls.model is None:
            return cls.DEFAULT
        domain = db.scalars(
>           select(cls.model.domain_id).where(cls.model.id == id_)
                   ^^^^^^^^^^^^^^^^^^^
        ).one_or_none()
E       AttributeError: type object 'Dataset' has no attribute 'domain_id'

app/core/authz/resolvers.py:49: AttributeError